// prelude.h — Shark 自身で実装されたコード（tools/prelude.py により自動生成）
//
// このファイルは自動生成されます。直接編集せず、stdlib/prelude.shk / prelude_ui.shk を編集してください。
#ifndef SHARK_PRELUDE_H
#define SHARK_PRELUDE_H

namespace shark {

static const char* kPreludeSource =
    "func __merge<T: Comparable>(ref xs: list<T>, lo: int, mid: int, hi: int) -> void {\n"
    "  var tmp: list<T> = [];\n"
    "  var a = lo;\n"
    "  var b = mid;\n"
    "  while a < mid && b < hi {\n"
    "    if xs[b].compare(xs[a]) < 0 {\n"
    "      tmp.push(xs[b]);\n"
    "      b = b + 1;\n"
    "    } else {\n"
    "      tmp.push(xs[a]);\n"
    "      a = a + 1;\n"
    "    }\n"
    "  }\n"
    "  while a < mid { tmp.push(xs[a]); a = a + 1; }\n"
    "  while b < hi { tmp.push(xs[b]); b = b + 1; }\n"
    "  var k = 0;\n"
    "  while k < tmp.len() {\n"
    "    xs[lo + k] = tmp[k];\n"
    "    k = k + 1;\n"
    "  }\n"
    "}\n"
    "\n"
    "func __sort<T: Comparable>(ref xs: list<T>) -> void {\n"
    "  var n = xs.len();\n"
    "  if n < 2 { return; }\n"
    "  var width = 1;\n"
    "  while width < n {\n"
    "    var i = 0;\n"
    "    while i < n {\n"
    "      var mid = i + width;\n"
    "      var hi = i + width + width;\n"
    "      if mid > n { mid = n; }\n"
    "      if hi > n { hi = n; }\n"
    "      __merge(ref xs, i, mid, hi);\n"
    "      i = i + width + width;\n"
    "    }\n"
    "    width = width + width;\n"
    "  }\n"
    "}\n"
    "\n"
    "// ui.action() のデフォルト戻り値。アクション関数が未設定のウィジェット用\n"
    "func __noop() -> void {\n"
    "}\n"
;

static const char* kUiRunSource =
    "import std.ui;\n"
    "\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> Widget,\n"
    "                update: func(string) -> void,\n"
    "                resizable: bool) -> void {\n"
    "  // サーフェス解像度はディスプレイの物理ピクセルと 1:1 に設定。丸めを行わない論理ピクセル比を使用する\n"
    "  // （Windows の 125% やブラウザズームなど小数スケールでのぼやけを防止）\n"
    "  var r = ui.pixel_ratio();\n"
    "  ui.open(title, int(float(width) * r + 0.5), int(float(height) * r + 0.5), resizable);\n"
    "  if ui.font_name() == \"\" { _ = ui.font(int(12.0 * r + 0.5)); }\n"
    "\n"
    "  // ヘッドレス環境（SHARK_UI=off 等）では、1 フレームのみ描画して復帰する。\n"
    "  // サーフェスは保持されるため、ui.get() や ui.to_png() で出力結果の取得が可能\n"
    "  if !ui.visible() {\n"
    "    ui.clear();\n"
    "    _ = ui.show(view());\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  while ui.poll() {\n"
    "    ui.clear();\n"
    "    var hit = ui.show(view());\n"
    "    var changed = ui.edited();    // ref でバインドされた入力欄が変数を更新したか判定\n"
    "    if ui.has_action() {          // ウィジェットのアクション関数が設定されていれば実行\n"
    "      var act = ui.action();\n"
    "      act();\n"
    "      changed = true;\n"
    "    }\n"
    "    if hit != \"\" {                // ウィジェットID が返却されていれば update を実行\n"
    "      update(hit);\n"
    "      changed = true;\n"
    "    }\n"
    "    if changed {                  // 状態が変更されたため即時再描画\n"
    "      ui.clear();\n"
    "      _ = ui.show(view());\n"
    "    }\n"
    "    ui.present();\n"
    "    ui.frame();\n"
    "  }\n"
    "  ui.close();\n"
    "}\n"
    "\n"
    "// resizable を省略したオーバーロード。ウィンドウのリサイズは有効（true）となる\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> Widget,\n"
    "                update: func(string) -> void) -> void {\n"
    "  run(title, width, height, view, update, true);\n"
    "}\n"
    "\n"
    "// update を省略したオーバーロード。各ウィジェットの個別 action コールバックを使用する\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> Widget) -> void {\n"
    "  run(title, width, height, view, __ui_ignore, true);\n"
    "}\n"
    "\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> Widget, resizable: bool) -> void {\n"
    "  run(title, width, height, view, __ui_ignore, resizable);\n"
    "}\n"
    "\n"
    "func __ui_ignore(hit: string) -> void {\n"
    "}\n"
    "\n"
    "// セル生成関数からグリッドウィジェットを構築。cell(row, col) が返却するウィジェットを行優先で配置する。\n"
    "// 内部的に ui.grid(cols, cells) を生成（core/lib/ui.cpp 参照）\n"
    "public func grid(rows: int, cols: int, cell: func(int, int) -> Widget) -> Widget {\n"
    "  var cells: list<Widget> = [];\n"
    "  for var r in range(rows) {\n"
    "    for var c in range(cols) {\n"
    "      cells.push(cell(r, c));\n"
    "    }\n"
    "  }\n"
    "  return ui.grid(cols, cells);\n"
    "}\n"
;


}  // namespace shark
#endif
