// prelude.h — Shark 自身で書いた部分（tools/prelude.py が stdlib/prelude.shk から作る）
//
// ここを直さない。直すのは stdlib/prelude.shk。
#ifndef SHARK_PRELUDE_H
#define SHARK_PRELUDE_H

namespace shark {

static const char* kPreludeSource =
    "func __merge<T: Comparable>(ref xs: list<T>, lo: int, mid: int, hi: int) -> void {\n"
    "  var tmp: list<T> = [];\n"
    "  var a = lo;\n"
    "  var b = mid;\n"
    "  while a < mid && b < hi {\n"
    "    if xs[b].compare(xs[a]) < 0 {\n"
    "      tmp.push(xs[b]);\n"
    "      b = b + 1;\n"
    "    } else {\n"
    "      tmp.push(xs[a]);\n"
    "      a = a + 1;\n"
    "    }\n"
    "  }\n"
    "  while a < mid { tmp.push(xs[a]); a = a + 1; }\n"
    "  while b < hi { tmp.push(xs[b]); b = b + 1; }\n"
    "  var k = 0;\n"
    "  while k < tmp.len() {\n"
    "    xs[lo + k] = tmp[k];\n"
    "    k = k + 1;\n"
    "  }\n"
    "}\n"
    "\n"
    "func __sort<T: Comparable>(ref xs: list<T>) -> void {\n"
    "  var n = xs.len();\n"
    "  if n < 2 { return; }\n"
    "  var width = 1;\n"
    "  while width < n {\n"
    "    var i = 0;\n"
    "    while i < n {\n"
    "      var mid = i + width;\n"
    "      var hi = i + width + width;\n"
    "      if mid > n { mid = n; }\n"
    "      if hi > n { hi = n; }\n"
    "      __merge(ref xs, i, mid, hi);\n"
    "      i = i + width + width;\n"
    "    }\n"
    "    width = width + width;\n"
    "  }\n"
    "}\n"
    "\n"
    "// ui.action() が返す既定。押された部品が関数を持っていないとき用\n"
    "func __noop() -> void {\n"
    "}\n"
;

static const char* kUiRunSource =
    "import std.ui;\n"
    "\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> list<Widget>,\n"
    "                update: func(string) -> void) -> void {\n"
    "  var k = ui.scale();\n"
    "  ui.open(title, width * k, height * k);\n"
    "  if ui.font_name() == \"\" { _ = ui.font(12 * k); }\n"
    "\n"
    "  // 画面が無いところ（SHARK_UI=off など）では、1回だけ描いて返る。\n"
    "  // 面はそのままにしておくので、ui.get() や ui.to_png() で結果を見られる\n"
    "  if !ui.visible() {\n"
    "    ui.clear();\n"
    "    _ = ui.show(view());\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  while ui.poll() {\n"
    "    ui.clear();\n"
    "    var hit = ui.show(view());\n"
    "    var changed = ui.edited();    // ref で受けた入力欄が、変数を書き換えた\n"
    "    if ui.has_action() {          // 部品が関数を持っていれば、それを呼ぶ\n"
    "      var act = ui.action();\n"
    "      act();\n"
    "      changed = true;\n"
    "    }\n"
    "    if hit != \"\" {                // 名札が付いていれば、update に渡す\n"
    "      update(hit);\n"
    "      changed = true;\n"
    "    }\n"
    "    if changed {                  // 状態が変わったので、すぐ描き直す\n"
    "      ui.clear();\n"
    "      _ = ui.show(view());\n"
    "    }\n"
    "    ui.present();\n"
    "    sleep(0.016);\n"
    "  }\n"
    "  ui.close();\n"
    "}\n"
    "\n"
    "// 部品に関数を持たせる書き方。update は要らない\n"
    "public func run(title: string, width: int, height: int,\n"
    "                view: func() -> list<Widget>) -> void {\n"
    "  run(title, width, height, view, __ui_ignore);\n"
    "}\n"
    "\n"
    "func __ui_ignore(hit: string) -> void {\n"
    "}\n"
;


}  // namespace shark
#endif
